apiVersion: v1
kind: Secret
metadata:
  name:  "{{ .Values.tezos.name }}-env"
type: Opaque
data:
  DATA_DIR: {{ .Values.tezos.base_path | b64enc }}
  WORK_DIR: {{ .Values.tezos.workdir_path | b64enc }}
  NODE_RPC_PORT: {{ .Values.service.rpcPort | b64enc }}
  NODE_HOST: {{ "localhost" | b64enc }}
  PROTOCOL: {{ .Values.tezos.protocol | b64enc }}
  BAKER_ALIAS: {{ .Values.tezos.baker_alias | b64enc }}
  BAKER_PASSWORD: {{ .Values.tezos.baker_password | b64enc }}
  BAKER_ADDRESS: {{ .Values.tezos.baker_address | b64enc }}